plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    id("com.google.gms.google-services")
}

android {
    namespace = 'com.example.mainchameleon'
    compileSdk = 34

    defaultConfig {
        applicationId = "com.example.mainchameleon"
        minSdk = 27
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles(
                    getDefaultProguardFile("proguard-android-optimize.txt"),
                    "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    viewBinding {
        enabled = true
    }
}

dependencies {
    // Core AndroidX Libraries
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.navigation.runtime.ktx
    implementation libs.androidx.navigation.fragment
    implementation libs.androidx.navigation.ui.ktx
    implementation libs.recyclerview

    // Material Design Components
    implementation libs.material

    // SwipeRefreshLayout (required for pull-to-refresh functionality)
    implementation libs.androidx.swiperefreshlayout

    // Firebase BOM (ensures consistent versions of Firebase libraries)
    implementation platform(libs.firebase.bom)
    implementation libs.firebase.storage.ktx
    implementation libs.firebase.database.ktx
    implementation libs.firebase.auth.ktx

    // CameraX (for custom camera functionality)
    implementation(libs.androidx.camera.core)
    implementation(libs.androidx.camera.camera2.v120)
    implementation(libs.androidx.camera.lifecycle.v120)
    implementation(libs.androidx.camera.view.v120)

    // Image Loading Libraries
    implementation libs.glide
    implementation libs.picasso
    implementation libs.firebase.crashlytics.buildtools

    // Testing Libraries
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core

    implementation libs.gson
}
